# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7100976fcc0306aeab32e9c22f61ea511e8d7012a13036565ecd342ea2fcfe4d65e152e63bcdaf45bd3204eb197768a9f3129605900aa9b8ef1c56b1c1ff71d9

test:
  secret_key_base: bd79a5d412d743eaa16477152d94f50ff7f29a802e0b413e4c44b43d40a05fad73fb3998a05099f221b28355bf56bbf9a047de5d8ece7c930a1683a448da3960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
